apiVersion: v1
kind: Service
metadata:
  labels:
    app: rconfig
  name: rconfig
spec:
  ports:
  - name: 8080-30080
    nodePort: 30004
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: rconfig
  type: NodePort
