apiVersion: v1
kind: Service
metadata:
  labels:
    app: flink
  name: flink
spec:
  ports:
  - name: 8081-30006
    nodePort: 30006
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: flink
  type: NodePort
